spring:
  application:
    name: central-monitoring-service

server:
  port : 8084

job:
  nats:
    uri: nats://localhost:4222
    temp-topic-name: TEMP
    humidity-topic-name: HUMIDITY

threshold:
  temp: 45
  humidity: 15
